sudo: true

dist: xenial

install:
        - sudo apt-get -y update
        - sudo apt-get -y install build-essential
        - sudo apt-get -y install parallel

script:
        - make
        - bash ./travis/RunSmokeTests.sh
        - bash ./travis/CheckSmokeResults.sh --test-errors smoke_tests.out --test-cross-section smoke_tests_1.out
